### ISSUE TITLE
discrete_uniform broken by autograd 1.1.3

### ISSUE THREAD

**Issue by gbarta** [mcleonard/sampyl#14]
Hi, thanks for the interesting library!

I was playing with the German Tank Problem example, and initially had trouble getting it to work - it would throw "TypeError: data type not understood" while computing the logp.

This turns out to only be a problem when using autograd 1.1.3 - the previous version 1.1.2 works fine.  It happens because autograd now wraps numpy.int_ as a new function, which breaks the integral type check in discrete_uniform: `if x.dtype != np.int_:` because it is not checking against the real np.int_.

Currently it appears that discrete_uniform is only used by the tank example.

I am inclined to think that if autograd is going to wrap np.int_ then it should also make it work transparently in the numpy type hierarchy, but I don't know enough about numpy internals to know how that might be done.

A possible workaround is to replace the check with `if x.dtype.kind in "iu":`.  I guess another is to use the unwrapped numpy to get access to numpy.int_, although it might be confusing to have two references to numpy which are not safely interchangeable.

**Comment by mattjj** [comment]
Autograd dev here. Great catch and diagnosis. I agree that this is really an autograd bug. Can you open an issue on our issue tracker?

We [wrapped `np.int_`](https://github.com/HIPS/autograd/commit/803d82d00ca5e2b573aa0ba86f4b9b29b120415f#diff-807a60a0ce8ef9fc90fa6ce6f5f9fd67R18) in a new function to fix [#71](https://github.com/HIPS/autograd/issues/71). One fix for this issue would be to wrap it instead in a class that also overrides `__eq__`. That would fix the dtype check here (though something like `if x.dtype is np.int_` would remain broken). Let me know if you have thoughts on that solution. Another fix would be to undo the commit that fixed our [#71](https://github.com/HIPS/autograd/issues/71), since it was kind of an edge case.

(Tangentially, autograd also breaks some subclass checks like `isinstance(x, tuple)` and `isinstance(x, np.ndarray)` because `TupleNode` doesn't subclass `tuple` due to its use of `__slots__` and `ArrayNode` doesn't subclass `np.ndarray`.)

**Comment by mattjj** [comment]
I think the autograd commit that closed [autograd #81](https://github.com/HIPS/autograd/issues/81) should fix this problem. @gbarta, can you check and update either here or in the autograd tracker?
